apps/comments/urls.py
from django.urls import path
from apps.comments import views

app_name = 'comments'

urlpatterns = [
    # path('api-data/', views.comment_all_data, name='api-comment'),
    path('post/<str:post_id>/', views.get_comments_post, name='get-comment-post'),
    path('add-update-comment/', views.add_update_comment_view, name='add-update-comment'),
    path('delete-comment/', views.delete_comment, name='delete-comment'),
    path('like/', views.like_comment, name='like-comment'),
]

apps/post/urls.py
from apps.post import views
from django.urls import path

app_name = 'post'

urlpatterns = [
    path('', views.post_create_list_view, name='post_list'),
    path('post-detail/<str:uid>/', views.post_detail_view, name='post_detail'),
    # path('add-post/', views.add_post, name='add_post'),
    path('delete-post/<str:uid>/', views.delete_post, name='delete_post'),
    path('update-post/<str:uid>/', views.update_post, name='update_post'),
    path('like/', views.like_post, name='like_post'),
]

apps/profiles/urls.py
from django.urls import path
from apps.profiles import views

app_name = 'profiles'

urlpatterns = [
    # path('<int:id>/<str:firstname>', views.profile, name='profile'),
    path('<str:pseudo>/', views.profile, name='profile'),
    path('profile/update/', views.update_profile, name='update_profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = i18n_patterns(
    path(f"admin/mackdin/{settings.UID_ADMIN}/", admin.site.urls, name="admin"),
    path("", include("apps.home.urls")),
    path("accounts/", include("apps.users.urls")),
    path("profile/", include("apps.profiles.urls")),
    path("feed/", include("apps.post.urls")),
    path("comment/", include("apps.comments.urls")),
    path("mynetwork/", include("apps.friends.urls")),
    path("notifications/", include("apps.notifications.urls")),
    path("messagerie/", include("apps.chat.urls")),
) + [path("accounts/", include("allauth.urls"))]

if settings.ENV == "development":
    urlpatterns += i18n_patterns(path("admin/i18n/", include("rosetta.urls"))) + [
        path("__debug__/", include("debug_toolbar.urls"))
    ]
    if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    else:
        urlpatterns += [
            re_path(
                r"^mediafiles/(?P<path>.*)$",
                serve,
                {"document_root": settings.MEDIA_ROOT},
            ),
        ]

    # import debug_toolbar
    # from rest_framework import routers
    # from apps.notifications.api.urls import router as router_notifications

    # router = routers.DefaultRouter()
    # router.registry.extend(router_notifications.registry)

    # urlpatterns += [
    #     path('api/', include('apps.profiles.api.urls')),
    #     path('api/', include('apps.notifications.api.urls')),
    #     # path('api/', include(router.urls)),
    #     # path('__debug__/', include(debug_toolbar.urls)),
    # ]
else:
    urlpatterns += [
        re_path(
            r"^mediafiles/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}
        ),
    ]

apps/post/models.py
import uuid

from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django.core.validators import FileExtensionValidator

from apps.utils.function import rename_post_img_video

User = get_user_model()

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')
    uid = models.CharField(_("code post"), max_length=500, blank=True)
    message = models.TextField(_("message"), blank=True)
    
    # cloudinary will be used to upload images and videos eslse
    # img = CloudinaryField(_("image"), blank=True, null=True)
    img = models.ImageField(_("image"), upload_to=rename_post_img_video, validators=[FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])], blank=True, null=True)
    img_str = models.CharField(max_length=500, blank=True, null=True)
    is_fixture = models.BooleanField(default=False)
    video = models.FileField(_("video"), upload_to=rename_post_img_video, blank=True, null=True)
    date_created = models.DateTimeField(_("date created"), auto_now_add=True)
    date_updated = models.DateTimeField(_("date updated"), auto_now=True)
    liked = models.ManyToManyField(User, related_name='user_like', blank=True, default=None)

    def __str__(self):
        return f"Post-{self.id}-{self.author.first_name}"
    
    def save(self, *args, **kwargs):
        if self.uid == "":
            self.uid = str(uuid.uuid4()).replace('-', '') + str(uuid.uuid4()).replace('-', '') + str(uuid.uuid4()).replace('-', '') + str(uuid.uuid4()).replace('-', '') + str(uuid.uuid4()).replace('-', '') + str(uuid.uuid4()).replace('-', '') + str(uuid.uuid4()).replace('-', '') + str(uuid.uuid4()).replace('-', '') + str(uuid.uuid4()).replace('-', '') + str(uuid.uuid4()).replace('-', '') + str(self.id)
        return super().save(*args, **kwargs)
    
    @property
    def number_of_like(self):
        return self.liked.all().count()
    
    class Meta:
        verbose_name = _('Post')
        verbose_name_plural = _('Posts')
        ordering = ('-date_created',)

class LikePost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    LIKE_CHOICES = (
        ('Like', 'Like'),
        ('Unlike', 'Unlike'),
    )
    value = models.CharField(choices=LIKE_CHOICES, max_length=10)
    
    def __str__(self):
        return f"Auteur: {self.user.first_name} {self.user.last_name}   -   PostId: {self.post.id}"

apps/post/forms.py
from django import forms
from django.forms import fields
from apps.post.models import Post
from django.utils.translation import gettext_lazy as _


class PostForm(forms.ModelForm):
    """Form definition for Post."""
    message = forms.CharField(required=False, widget=forms.Textarea(
        attrs={'rows':'2', 'id':'textarea_id', 'placeholder': _('Ajouter un post')}))
    img = forms.ImageField(required=False, widget=forms.FileInput(
        attrs={'id':'file', 'class':'form-input-file'}))
    class Meta:
        """Meta definition for Postform."""
        model = Post
        fields = ('message', 'img',)

    def clean(self, *args, **kwargs):
        msg = self.cleaned_data.get('message')
        img = self.cleaned_data.get('img')
        if (msg is None or msg == '') and (img is None):
            raise forms.ValidationError(_("Veuillez saisir un message ou télécharger une image"))

apps/post/views.py
import os
import cloudinary

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.paginator import Paginator
from django.http import (
    HttpResponse,
    HttpResponseNotFound,
    HttpResponsePermanentRedirect,
    HttpResponseRedirect,
    JsonResponse,
)
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page
from django.core.cache import cache

from apps.notifications.models import Notification
from apps.profiles.models import Profile
from apps.comments.views import comment_view
from apps.post.models import LikePost, Post
from apps.post.forms import PostForm


@login_required(login_url="sign_in")
def post_create_list_view(
    request, *args, **kwargs
) -> HttpResponseRedirect | HttpResponsePermanentRedirect | HttpResponse:
    page = request.GET.get("page")
    if page is None:
        page = 1
    posts = cache.get(f"posts_list_{page}")

    if posts is None:
        _posts = (
            Post.objects.select_related("author").prefetch_related("post_comment").all()
        )
        current_user = Profile.objects.select_related("user").get(user=request.user)

        paginator = Paginator(_posts, 6)
        num = paginator.num_pages

        if int(page) > num:
            return HttpResponseNotFound("<h1>Page not found 404</h1>")

        posts = paginator.get_page(page)
        try:
            cache.set(f"posts_list_{page}", posts, 60 * 60 * 24)
        except Exception:
            pass

    AddPostForm = PostForm()

    if "submit_p_form" in request.POST:
        AddPostForm = PostForm(request.POST, request.FILES)
        if AddPostForm.is_valid():
            instance = AddPostForm.save(commit=False)
            instance.author = request.user
            instance.save()
            AddPostForm = PostForm()

            # notifier pour le nouveau post aux amis
            if request.user.friends:
                for to_user in request.user.friends.all():
                    Notification.objects.create(
                        type_notif="Add_Post",
                        from_user=request.user,
                        to_user=to_user.user,
                        post=instance,
                    )

            return redirect("post:post_list")

    context = {
        "start_animation": "feed",
        "posts": posts,
        "AddPostForm": AddPostForm,
        "page": "list",
        "domain": get_current_site(request),
        "is_ajax": request.is_ajax(),
        "page_number": page,
    }
    context.update(comment_view(request))

    if request.is_ajax():
        return render(request, "post/components/post-detail.html", context)

    return render(request, "post/post_list.html", context)


@cache_page(60 * 15)
@login_required(login_url="sign_in")
def post_detail_view(request, uid):
    try:
        post = (
            Post.objects.select_related("author")
            .prefetch_related("post_comment")
            .get(uid=uid)
        )
    except:
        return HttpResponseNotFound("<h1>Page not found</h1>")

    template = "post/post_list.html"
    context = {
        "start_animation": "feed",
        "posts": [post],
        "page": "detail",
    }
    context.update(comment_view(request))
    return render(request, template, context)


@login_required(login_url="sign_in")
def update_post(request, uid):
    post_edit = get_object_or_404(Post, uid=uid)
    if post_edit.author != request.user:
        return HttpResponseNotFound("<h1>Page Not Found 404</h1>")
    posts = Post.objects.all()
    if request.method == "POST":
        if len(request.FILES) != 0:
            if post_edit.img:
                if len(post_edit.img) > 0:
                    if settings.ENV == "production":
                        cloudinary.uploader.destroy(str(post_edit.img))
                    else:
                        try:
                            os.remove(post_edit.img.path)
                        except:
                            cloudinary.uploader.destroy(str(post_edit.img))
            post_edit.img = request.FILES["img"]
        post_edit.message = request.POST.get("message")
        post_edit.save()
        return redirect("post:post_list")

    template = "post/post_list.html"
    context = {
        "start_animation": "feed",
        "posts": posts,
        "post_edit": post_edit,
        "page": "update",
    }
    return render(request, template, context)


# def add_post(request):
#     user = request.user
#     AddPostForm = PostForm(request.POST or None, request.FILES or None)
#     if request.is_ajax():
#         if AddPostForm.is_valid():
#             instance = AddPostForm.save(commit=False)
#             instance.author = user
#             instance.save()
#             post = Post.objects.values()
#             return JsonResponse({'status': 'success', 'post_data': list(post)})
#         else:
#             return JsonResponse({'status': 'error'})


@login_required(login_url="sign_in")
def delete_post(request, uid):
    user = request.user
    # if request.method == 'POST':
    #     p_id = request.POST.get('post_id')
    #     instance = Post.objects.get(pk=p_id)
    #     if user == instance.author:
    #         instance.delete()
    #         return JsonResponse({'status': 'Post supprimer'})
    # else:
    #     return JsonResponse({'status': 'error'})
    instance = get_object_or_404(Post, uid=uid)
    if user == instance.author:
        instance.delete()
    return redirect("post:post_list")


@login_required(login_url="sign_in")
def like_post(request):
    user = request.user
    if request.method == "POST":
        post_id = request.POST.get("post_id")
        post_obj = Post.objects.get(id=post_id)
        if user in post_obj.liked.all():
            post_obj.liked.remove(user)
        else:
            post_obj.liked.add(user)
        like, created = LikePost.objects.get_or_create(user=user, post_id=post_id)
        if not created:
            if like.value == "Like":
                like.value = "Unlike"
            else:
                like.value = "Like"
        else:
            like.value = "Like"

        post_obj.save()
        like.save()

        data = {
            "value": str(like.value),
        }
        return JsonResponse(data, safe=False)
    return redirect("post:post_list")

templates/post/components/add_post.html
{% load static %}
{% load cloudinary %}
{% load i18n %}


<div class="new-add-post">
  <div class="new-add-post1">
    <a href="{% url 'profiles:profile' pseudo=user.profile.pseudo  %}">
      <div class="new-add-post-left-container">
        <img src="        
          {% if user.profile.is_fixture %}
            {{ user.profile.img_profile_str }}
          {% else %}
            {% if user.profile.img_profile %}
              {{ user.profile.img_profile.url }}
            {% else %}
              {% static 'home/img/default-img-profile.jpg' %}
            {% endif %}
          {% endif %}
      " alt="">
      </div>
    </a>
    <div class="new-add-post-right-container">
      <form class="form-new-add-post" action="" method="POST" enctype="multipart/form-data" id="form-add-new-post">
        {% csrf_token %}
        <div class="input-text">
          {% if page == 'update' %}
          <textarea name="message" id="textarea_id" cols="65" rows="2"
            placeholder="Ajouter un post">{{post_edit.message}}</textarea>
          {% else %}
          {{ AddPostForm.message }}
          {% endif %}
        </div>
        <div class="add-img-btn-send">
          <div class="input-file">
            {% if page == 'update' %}
            <input type="file" name="img" id="file" class="form-input-file">
            {% else %}
            {{ AddPostForm.img }}
            {% endif %}
            <label for="file" class="form-lable">
              <img src="{% static 'home/svg/gal.svg' %}" alt="">
              <span>{% translate "Ajouter une photo" %}</span>
            </label>
          </div>
          <button id="btn-add-new-post" type="submit" name="submit_p_form">
            <span>{% translate "Publier" %}</span>
            <img src="{% static 'home/svg/send.svg' %}" alt="">
          </button>
        </div>
      </form>
    </div>
  </div>

  <div class="previous-new-add-post">
    <div class="previous-post-container">
      <div class="previous-post-box">
        <p id="Previsualisation">{% translate "Prévisualisation de votre post :" %}</p>
        <div class="previous-post-header">
          <div class="previous-post-header-img">
            <img src="                   
              {% if user.profile.is_fixture %}
                {{ user.profile.img_profile_str }}
              {% else %}
                {% if user.profile.img_profile %}
                  {{ user.profile.img_profile.url }}
                {% else %}
                  {% static 'home/img/default-img-profile.jpg' %}
                {% endif %}
              {% endif %}
            " alt="">
          </div>
          <div class="previous-post-header-info">
            <strong></strong>
            <p id='bio'>
              {% if user.profile.bio %}
              {{ user.profile.bio }}
              {% endif %}
            </p>
            <p id='date_created'>{% now "jS F Y H:i" %}</p>
          </div>
        </div>

        <div class="previous-post-text-content">
          <p id='previous-message'>{% if page == 'update' %}{{post_edit.message}}{% endif %}</p>
        </div>

        <div class="previous-post-img">
          {% if page == 'update' %}
          <img id='previous-post-image' src="{% if post_edit.img %} {{post_edit.img.url}} {% endif %}">
          {% else %}
          <img id='previous-post-image' src="">
          <img id="close-img-previous" src="{% static 'home/svg/clos.svg' %}" alt="">
          {% endif %}
        </div>

      </div>
    </div>
    <div class="cancel-add-post-container">
      {% if page == 'update' %}
      <a href="{% url 'post:post_list' %}">
        <span id="btn-cancel-add-post">{% translate "Annuler" %}</span>
      </a>
      {% else %}
      <span id="btn-cancel-add-post">{% translate "Annuler" %}</span>
      {% endif %}
    </div>
  </div>
</div>

templates/post/components/block-js.html
{% load static %}


<script type="text/javascript" src=" {% static 'components/js/index.js' %} "></script>
<script type="text/javascript" src=" {% static 'notifications/js/notifications.js' %} "></script>
<script type="text/javascript" src=" {% static 'post/js/post_list.js' %} "></script>
<script type="text/javascript" src=" {% static 'post/js/ajax_like_post.js' %} "></script>
<script type="text/javascript" src=" {% static 'comments/js/comment_list.js' %} "></script>
<script type="text/javascript" src=" {% static 'post/js/api-news.js' %} "></script>

<!-- react js -->
{% comment %}
<!-- <script src="https://unpkg.com/react@18/umd/react.development.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js" crossorigin></script> -->
{% endcomment %}
<script src="https://unpkg.com/react@18/umd/react.production.min.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js" crossorigin></script>

<script src=" {% static 'comments/js/react/build/components/InfoLikeComment.js' %} "></script>
<script src=" {% static 'comments/js/react/build/components/BtnLikeCommentShare.js' %} "></script>
<script src=" {% static 'comments/js/react/build/components/InputForm.js' %} "></script>
<script src=" {% static 'comments/js/react/build/components/OptionComment.js' %} "></script>
<script src=" {% static 'comments/js/react/build/components/ListComments.js' %} "></script>
<script src=" {% static 'comments/js/react/build/comments.js' %} "></script>
<script src=" {% static 'comments/js/react/build/index.js' %} "></script>



{% comment %}
{% include 'post/components/ajax_like_post.html' %}
{% include 'comments/include/ajax_comment.html' %}
{% endcomment %}

{% if page == 'update' %}
<script>
  const previous_container_edit = document.querySelector(
    ".previous-new-add-post"
  );
  const previous_p_img_container_edit =
    document.querySelector(".previous-post-img");

  previous_container_edit.classList.remove("display-none");
  previous_container_edit.classList.add("display-block");

  previous_p_img_container_edit.classList.remove("display-none");
  previous_p_img_container_edit.classList.add("display-block");
</script>
{% endif %}
{% if page == 'list' %}
<script>
  try {
    // Close image previous
    const close_previous_p_img_container = document.querySelector(".previous-post-img");
    const close_input_img = document.querySelector(".form-input-file");
    const close_p_img = document.getElementById("previous-post-image");
    const closed_img_previous = document.getElementById("close-img-previous");

    closed_img_previous.addEventListener("click", (e) => {
      close_previous_p_img_container.classList.remove("display-none");
      close_previous_p_img_container.classList.remove("display-block");
      close_input_img.value = ''
      close_p_img.setAttribute("src", "");
    })
  } catch (error) { }

  paginatorWithAjax("", ".container-main", ".container-main", "{{ csrf_token }}", 50, true);
</script>

{% elif page == 'notif' %}
<script>
  paginatorWithAjax("", ".container-notif", ".container-notif", "{{ csrf_token }}", 0)
</script>
{% endif %}

templates/post/components/count-likes-comments.html
{% load static %}
{% load i18n %}


<div class="count-likes-comments">
  <div id="likes-count{{post.id}}">

    <span id="likes-num{{post.id}}">{{post.number_of_like}}</span>
    <span id="text-plural{{post.id}}">
      {% if post.number_of_like > 1 %}
      Likes
      {% else %}
      Like
      {% endif %}
    </span>

  </div>
  <div class="comments-count-post" id="comments-count{{post.id}}">

    <span id="comments-num{{post.id}}">{{post.post_comment.count}}</span>
    <span id="text-plural-comments{{post.id}}">
      {% if post.post_comment.count > 1 %}
      {% translate "Commentaires" %}
      {% else %}
      {% translate "Commentaire" %}
      {% endif %}
    </span>

  </div>
</div>

templates/post/components/left.html
{% load static %}
{% load humanize %}
{% load cloudinary %}
{% load i18n %}


<div class="left-sub-container">
  <div class="left-container-bg-img">
    <img src="        
      {% if request.user.profile.is_fixture %}
        {{ request.user.profile.img_bg_str }}
      {% else %}
        {% if request.user.profile.img_bg %}
          {{ request.user.profile.img_bg.url }}
        {% else %}
          {% static 'home/img/default-img-bg.jpg' %}
        {% endif %}
      {% endif %}
    " class=left-bg-img />
  </div>

  <a href="{% url 'profiles:profile' pseudo=request.user.profile.pseudo  %}">
    <img src="
      {% if request.user.profile.is_fixture %}
        {{ request.user.profile.img_profile_str }}
      {% else %}
        {% if request.user.profile.img_profile %}
          {{ request.user.profile.img_profile.url }}
        {% else %}
          {% static 'home/img/default-img-profile.jpg' %}
        {% endif %}
      {% endif %}
  " class="left-img-profile" />
  </a>

  <div class="left-container-info">
    <a href="{% url 'profiles:profile' pseudo=request.user.profile.pseudo  %}">
      <h4>{{ request.user.first_name }} {{ request.user.last_name }}</h4>
    </a>
    <p>{{ request.user.profile.bio }}</p>
  </div>

  <hr>

  <div class="post-left-statistic-profile">
    <div class="post-left-num-vue statistic">
      <span class="post-left-statistic-text">{% translate "Vues de votre profil" %}</span>
      <span class="post-left-statistic-num">
        {% if request.user.profile.number_views %}
        {{request.user.profile.number_views}}
        {% else %}
        0
        {% endif %}
      </span>
    </div>
    <div class="post-left-num-post statistic">
      <span class="post-left-statistic-text">{% translate "Nombre de post" %}</span>
      <span class="post-left-statistic-num">{{request.user.post.count}}</span>
    </div>
  </div>
</div>

templates/post/components/like-form-btn.html
{% load static %}
{% load i18n %}

<form action="{% url 'post:like_post' %}" method="POST" class="like-form" id="{{post.id}}">
    {% csrf_token %}
    <input type="hidden" name="post_id" value="{{post.id}}" />
    <button type="submit" class="like-btn{{post.id}}">
        {% if user not in post.liked.all %}
        <img id="like-img{{post.id}}" class="icon-like-comment-share" src="{% static 'home/svg/unlike.svg' %}" />
        <span class="like-text{{post.id}} label-like-comment-share">{% translate "J'aime" %}</span>
        {% else %}
        <img id="like-img{{post.id}}" class="icon-like-comment-share" src="{% static 'home/svg/like.svg' %}" />
        <span class="like-text{{post.id}} text-like_unlike-span label-like-comment-share">{% translate "J'aime" %}</span>
        {% endif %}
    </button>
</form>

templates/post/components/options.html
{% load static %}
{% load i18n %}

{% if request.user == post.author %}
<div id="{{post.id}}" class="options-btn">
  <span id="btn-point"></span>
  <span id="btn-point"></span>
  <span id="btn-point"></span>
</div>

<div id="options-container{{post.id}}" class="options-actions-container display-none">
  <ul>
    <a href="{% url 'post:update_post' post.uid  %}" class="options-item">
      <img src="{% static 'home/svg/edit.svg' %}">
      <span class="btn-edit-post" id="{{post.id}}">{% translate "Modifier" %}</span>
    </a>
    <a href="{% url 'post:delete_post' post.uid  %}" class="options-item options-delete-post">
      <img src="{% static 'home/svg/delete.svg' %}">
      <span class="btn-del-post" id="{{post.id}}">{% translate "Supprimer" %}</span>
    </a>
  </ul>
</div>
{% endif %}

templates/post/components/post-detail.html
{% load static %}
{% load humanize %}
{% load cloudinary %}
{% load chat %}

{% for post in posts %}

<div class="container-all-post">
  {% include 'post/components/options.html' %}
  <div class="post-header">
    <a href="{% url 'profiles:profile' pseudo=post.author.profile.pseudo  %}">
      <div class="post-header-img">
        <img src="        
            {% if post.author.profile.is_fixture %}
              {{ post.author.profile.img_profile_str }}
            {% else %}
              {% if post.author.profile.img_profile %}
                {{ post.author.profile.img_profile.url }}
              {% else %}
                {% static 'home/img/default-img-profile.jpg' %}
              {% endif %}
            {% endif %}
          " />
      </div>
    </a>
    <div class="post-header-info">
      <strong><a href="{% url 'profiles:profile' pseudo=post.author.profile.pseudo  %}">{{post.author.first_name}}
          {{post.author.last_name}}</a></strong>
      <p>{{post.author.profile.bio}}</p>
      <p>{{post.date_created|naturaltime|timestr}}</p>
    </div>
  </div>

  <div class="post-text-content">
    <p>{{post.message|linebreaksbr}}</p>
  </div>

  {% if post.is_fixture %}
  <!-- <div class="post-img">
      <img src="{{post.img_str}}" alt="" />
    </div> -->
  {% elif post.img %}
  <div class="post-img">
    <img src="{{post.img.url}}" alt="" />
  </div>
  {% endif %}

  {% comment %}
  <!-- <div class="post-footer">
    {% include 'post/components/count-likes-comments.html' %}
    <hr />
    <div class="box-action-icon">
      {% include 'post/components/like-form-btn.html' %}
      <button href="#" class="action-icon box-comment btn-container-comment-toggle" id="{{post.id}}">
        <img src="{% static 'home/svg/comment.svg' %}" class="icon-like-comment-share" id="{{post.id}}" />
        <span id="{{post.id}}" class="label-like-comment-share">Commenter</span>
      </button>
      <button href="#" class="action-icon box-share">
        <img src="{% static 'home/svg/share.svg' %}" class="icon-like-comment-share" />
        <span class="label-like-comment-share">Partager</span>
      </button>
    </div>
  </div> -->
  {% endcomment %}

  <div class="root-comments {% if is_ajax != 'detail' %}root-comments-isAjax-{{page_number}}{% endif %}" data-post-id="{{ post.id }}"
    data-class-toggle-post-detail="{% if page != 'detail' %}1{% else %}0{% endif %}"
    data-url-add-update-comment="{% url 'comments:add-update-comment' %}" data-csrf-token="{{ csrf_token }}"
    data-img-profile="{% if user.profile.is_fixture %}{{ user.profile.img_profile_str }}{% else %}{% if user.profile.img_profile %}{{ user.profile.img_profile.url }}{% else %}{% static 'home/img/default-img-profile.jpg' %}{% endif %}{% endif %}"
    data-url-get-data="{% url 'comments:get-comment-post' post_id=post.id %}" data-nber-like="{{post.number_of_like}}"
    data-nber-comment="{{post.post_comment.count}}"
    data-is-like="{% if user not in post.liked.all %}0{% else %}1{% endif %}">
  </div>

  {% comment %}
  {% include 'comments/include/comment.html' %}
  {% endcomment %}
</div>

{% endfor %}