apps/chat/urls.py
from django.urls import path

from apps.chat import views

app_name = 'chats'

urlpatterns = [
    path('', views.chat_view, name='chat'),
    path('chatroom/<str:uid>/', views.chatroom, name='chatroom'),
    path('load-data/<str:uid>/', views.ajax_load_messages, name='chat-load-data'),
    path('chat-api-notif/', views.chat_api_view, name='chat-api-notif'),
]

apps/friends/urls.py
from django.urls import path
from apps.friends import views

app_name = 'friends'

urlpatterns = [
    path('', views.invites_list_profiles_view, name='my_network'),
    path('connections/', views.my_friends_invites_profiles_view, name='my_friends'),
    path('invitation-received/', views.invites_received_view, name='invitation_received'),
    path('invitation-send/', views.invites_sended_view, name='invitation_send'),
    
    path('invitation/accept/', views.accept_invitation, name='accept_invitation'),
    path('invitation/reject/', views.reject_invitation, name='reject_invitation'),
    path('invitation/cancel/', views.cancel_invitation, name='cancel_invitation'),
    
    path('invitation/send', views.send_invitation, name='send_invitation'),
    path('invitation/remove', views.remove_from_friends, name='remove_invitation'),
]

apps/home/urls.py
from django.urls import path
from apps.home import views

app_name = "home"

urlpatterns = [
    path("", views.home, name="home"),
]

apps/post/urls.py
from apps.post import views
from django.urls import path

app_name = 'post'

urlpatterns = [
    path('', views.post_create_list_view, name='post_list'),
    path('post-detail/<str:uid>/', views.post_detail_view, name='post_detail'),
    # path('add-post/', views.add_post, name='add_post'),
    path('delete-post/<str:uid>/', views.delete_post, name='delete_post'),
    path('update-post/<str:uid>/', views.update_post, name='update_post'),
    path('like/', views.like_post, name='like_post'),
]

apps/profiles/urls.py
from django.urls import path
from apps.profiles import views

app_name = 'profiles'

urlpatterns = [
    # path('<int:id>/<str:firstname>', views.profile, name='profile'),
    path('<str:pseudo>/', views.profile, name='profile'),
    path('profile/update/', views.update_profile, name='update_profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = i18n_patterns(
    path(f"admin/mackdin/{settings.UID_ADMIN}/", admin.site.urls, name="admin"),
    path("", include("apps.home.urls")),
    path("accounts/", include("apps.users.urls")),
    path("profile/", include("apps.profiles.urls")),
    path("feed/", include("apps.post.urls")),
    path("comment/", include("apps.comments.urls")),
    path("mynetwork/", include("apps.friends.urls")),
    path("notifications/", include("apps.notifications.urls")),
    path("messagerie/", include("apps.chat.urls")),
) + [path("accounts/", include("allauth.urls"))]

if settings.ENV == "development":
    urlpatterns += i18n_patterns(path("admin/i18n/", include("rosetta.urls"))) + [
        path("__debug__/", include("debug_toolbar.urls"))
    ]
    if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    else:
        urlpatterns += [
            re_path(
                r"^mediafiles/(?P<path>.*)$",
                serve,
                {"document_root": settings.MEDIA_ROOT},
            ),
        ]

    # import debug_toolbar
    # from rest_framework import routers
    # from apps.notifications.api.urls import router as router_notifications

    # router = routers.DefaultRouter()
    # router.registry.extend(router_notifications.registry)

    # urlpatterns += [
    #     path('api/', include('apps.profiles.api.urls')),
    #     path('api/', include('apps.notifications.api.urls')),
    #     # path('api/', include(router.urls)),
    #     # path('__debug__/', include(debug_toolbar.urls)),
    # ]
else:
    urlpatterns += [
        re_path(
            r"^mediafiles/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}
        ),
    ]

apps/home/models.py
from django.db import models

# Create your models here.

apps/home/views.py
import random
from apps.profiles.models import Profile
from django.shortcuts import redirect, render


def home(request):
    user = request.user
    template = "home/index.html"
    # template = "index.html"
    # mens = [f"https://randomuser.me/api/portraits/men/{i}.jpg" for i in range(0, 80)] + [f"https://xsgames.co/randomusers/assets/avatars/male/{i}.jpg" for i in range(0, 78)]
    # womens = [f"https://randomuser.me/api/portraits/women/{i}.jpg" for i in range(0, 80)] + [f"https://xsgames.co/randomusers/assets/avatars/female/{i}.jpg" for i in range(0, 78)]
    # images = mens + womens
    # random.shuffle(images)

    context = {
        'start_animation': 'home',
        # "images": images,
        # "l": len(images),
    }

    # return render(request, template, context=context)

    if user.is_authenticated:
        return redirect('post:post_list')
    
    return render(request, template, context=context)

templates/home/components/footer.html
{% load static %}

<footer>
  <div class="footer-content">
    <div class="footer-content-box">
      <a class="footer-logo" href="{% url 'home:home' %}">
        <img src="{% static 'home/img/logo3.jpg' %}" alt="logo Macktireh">
      </a>
    </div>

    <div class="footer-content-box ul-container">
      <ul>
        <li><a href="https://www.linkedin.com/in/macktireh/" target="_blank"><img
              src="{% static 'home/svg/linkedin.svg' %}" alt="Compte linkedin"></a></li>
        <li><a href="https://github.com/Macktireh" target="_blank"><img class="ml"
              src="{% static 'home/svg/github.svg' %}" alt="Compte github"></a>
        </li>
        <li><a href="https://twitter.com/macktireh" target="_blank"><img src="{% static 'home/svg/twitter.svg' %}"
              alt="Compte twitter"></a>
        </li>
      </ul>
    </div>
  </div>
  <!-- <hr>    -->
  <div class="footer-bottom">
    <p>Mackd<img src=" {% static 'home/svg/linkedin.svg' %} "> &copy;{% now 'Y' %} Macktireh AS | <a href="">Mentions
        légales</a></p>
  </div>
</footer>

templates/home/components/navbar-home.html
{% load static %}
{% load i18n %}

{% get_current_language as LANGUAGE_CODE %}

<style>
  @media screen and (max-width: 500px) {
    .nav-text-span {
      display: none;
    }
  }
    
  
</style>

<div class="nav-container">
  <div>
    <a class="logo logo1" href="{% url 'home:home' %}" style="color: #1abc9c">
      Mackd<img src=" {% static 'home/svg/linkedin-cust.svg' %} " alt="logo">
    </a>
  </div>
  <div>
    <nav style="padding-right: 15px">
      <ul class="nav-menu">
        {% if not user.is_authenticated %}
        <a href="{% url 'sign_in' %}" class="nav-item">
          <div class="nav-text">
            <img class="nav-img" src="{% static 'home/svg/user.svg' %}" alt="">
            <span class="animation {% if start_animation == 'sign_in' %}start-animation{% endif %}"></span>
            <span class="nav-text-span">{% translate "s'identifier" %}</span>
          </div>
        </a>
        <a href="{% url 'sign_up' %}" class="nav-item">
          <div class="nav-text">
            <img class="nav-img" src="{% static 'home/svg/signup.svg' %}" alt="">
            <span class="animation {% if start_animation == 'sign_up' %}start-animation{% endif %}"></span>
            <span>{% translate "S'inscrire" %}</span>
          </div>
        </a>
        <a href="/{% if LANGUAGE_CODE == 'fr' %}en{% else %}fr{% endif %}/" class="nav-item">
          <div class="nav-text">
            <img class="nav-img" src="{% static 'home/svg/language.svg' %}" alt="">
            <span class="animation {% if start_animation == 'sign_up' %}start-animation{% endif %}"></span>
          </div>
        </a>
        {% endif %}
      </ul>
    </nav>

    <div class="hamburger-nav-profil">
      <div class="hamburger">
        <span class="hamburger__bar"></span>
        <span class="hamburger__bar"></span>
        <span class="hamburger__bar"></span>
      </div>
    </div>
  </div>
</div>

templates/home/components/navbar2.html
{% load static %}
{% load cloudinary %}
{% load i18n %}

{% get_current_language as LANGUAGE_CODE %}

<div class="nav-container">
  <div>
    <a class="logo logo2" href="{% url 'home:home' %}">
      <img src=" {% static 'home/svg/linkedin-cust.svg' %} " alt="logo">
    </a>
  </div>
  
  <nav>
    <ul class="nav-menu">
      {% if not user.is_authenticated %}
      <a href="{% url 'sign_in' %}" class="nav-item">
        <div class="nav-text">
          <img class="nav-img" src="{% static 'home/svg/user.svg' %}" alt="">
          <span class="animation {% if start_animation == 'sign_in' %}start-animation{% endif %}"></span>
          <span class="nav-text-span">{% translate "s'identifier" %}</span>
        </div>
      </a>
      <a href="{% url 'sign_up' %}" class="nav-item">
        <div class="nav-text">
          <img class="nav-img" src="{% static 'home/svg/signup.svg' %}" alt="">
          <span class="animation {% if start_animation == 'sign_up' %}start-animation{% endif %}"></span>
          <span>{% translate "S'inscrire" %}</span>
        </div>
      </a>
      
      {% else %}
      <a href="{% url 'post:post_list' %}" class="nav-item">
        <div class="nav-text">
          <img class="nav-img" src="{% static 'home/svg/home.svg' %}" alt="">
          <span class="animation  {% if start_animation == 'feed' %}start-animation{% endif %}"></span>
          <span class="nav-text-span">{% translate 'Accueil' %}</span>
        </div>
      </a>
      <a href="{% url 'friends:my_network' %}" class="nav-item">
        <div class="nav-text">
          <img class="nav-img" src="{% static 'home/svg/friends.svg' %}" alt="">
          <span class="animation {% if start_animation == 'my_network' %}start-animation{% endif %}"></span>
          <span class="nav-text-span">{% translate 'Réseau' %}</span>
        </div>
      </a>
      <a href="{% url 'chats:chat' %}" class="nav-item nav-nofit">
        <span id="nav-nofit-alert-chat"></span>
        <div class="nav-text">
          <img class="nav-img" src="{% static 'home/svg/chat.svg' %}" alt="">
          <span class="animation {% if start_animation == 'chat' %}start-animation{% endif %}"></span>
          <span class="nav-text-span">{% translate 'Messagerie' %}</span>
        </div>
      </a>
      <a href="{% url 'notifications:notif' %}" class="nav-item nav-nofit" id="nav-nofit-icon">
        <span id="nav-nofit-alert"></span>
        <div class="nav-text">
          <img class="nav-img" src="{% static 'home/svg/notification.svg' %}" alt="">
          <span class="animation {% if start_animation == 'notif' %}start-animation{% endif %}"></span>
          <span class="nav-text-span">Notifications</span>
        </div>
      </a>
      {% endif %}
    </ul>
  </nav>

  {% if user.is_authenticated %}

  <div class="nav-profil">
    <div class="nav-box-profil">
      <img src="        
      {% if user.profile.is_fixture %}
        {{ user.profile.img_profile_str }}
      {% else %}
        {% if user.profile.img_profile %}
        {{ user.profile.img_profile.url }}
        {% else %}
        {% static 'home/svg/user.svg' %}
        {% endif %}
      {% endif %}
      " alt="">
    </div>
    <div class="drop-down-list">
      <span>{% translate 'Vous' %}</span>
      <img src="{% static 'home/svg/down-arrow.svg' %}" class="down-arrow">
    </div>
  </div>

  <div class="list-box">
    <a href="{% url 'profiles:profile' pseudo=user.profile.pseudo %}">
      <img src="{% static 'home/svg/user.svg' %}">
      <span class="text">Profil</span>
    </a>
    {% if user.is_staff %}
    <a href="{% url 'admin:index' %}" target="_blank">
      <img src="{% static 'home/svg/admin.svg' %}">
      <span class="text">Administration</span>
    </a>
    {% endif %}
    <a  id="language_code_link" style="cursor: pointer" href="/">
      <img src="{% static 'home/svg/language.svg' %}">
      <span class="text">{% if LANGUAGE_CODE == 'fr' %}{% translate 'Traduire en Anglais' %}{% else %}{% translate 'Traduire en Français' %}{% endif %}</span>
    </a>
    <a href="{% url 'logout' %}">
      <img src="{% static 'home/svg/logout.svg' %}">
      <span class="text">{% translate 'Déconnexion' %}</span>
    </a>
  </div>
  {% endif %}
</div>