apps/chat/urls.py
from django.urls import path

from apps.chat import views

app_name = 'chats'

urlpatterns = [
    path('', views.chat_view, name='chat'),
    path('chatroom/<str:uid>/', views.chatroom, name='chatroom'),
    path('load-data/<str:uid>/', views.ajax_load_messages, name='chat-load-data'),
    path('chat-api-notif/', views.chat_api_view, name='chat-api-notif'),
]

apps/friends/urls.py
from django.urls import path
from apps.friends import views

app_name = 'friends'

urlpatterns = [
    path('', views.invites_list_profiles_view, name='my_network'),
    path('connections/', views.my_friends_invites_profiles_view, name='my_friends'),
    path('invitation-received/', views.invites_received_view, name='invitation_received'),
    path('invitation-send/', views.invites_sended_view, name='invitation_send'),
    
    path('invitation/accept/', views.accept_invitation, name='accept_invitation'),
    path('invitation/reject/', views.reject_invitation, name='reject_invitation'),
    path('invitation/cancel/', views.cancel_invitation, name='cancel_invitation'),
    
    path('invitation/send', views.send_invitation, name='send_invitation'),
    path('invitation/remove', views.remove_from_friends, name='remove_invitation'),
]

apps/profiles/api/urls.py
from django.urls import path

from apps.profiles.api import views

app_name = 'api-profiles'

urlpatterns = [
    path('profiles/', views.get_list_profiles),
    path('profiles/<int:id>/', views.get_profile),
]

apps/profiles/urls.py
from django.urls import path
from apps.profiles import views

app_name = 'profiles'

urlpatterns = [
    # path('<int:id>/<str:firstname>', views.profile, name='profile'),
    path('<str:pseudo>/', views.profile, name='profile'),
    path('profile/update/', views.update_profile, name='update_profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = i18n_patterns(
    path(f"admin/mackdin/{settings.UID_ADMIN}/", admin.site.urls, name="admin"),
    path("", include("apps.home.urls")),
    path("accounts/", include("apps.users.urls")),
    path("profile/", include("apps.profiles.urls")),
    path("feed/", include("apps.post.urls")),
    path("comment/", include("apps.comments.urls")),
    path("mynetwork/", include("apps.friends.urls")),
    path("notifications/", include("apps.notifications.urls")),
    path("messagerie/", include("apps.chat.urls")),
) + [path("accounts/", include("allauth.urls"))]

if settings.ENV == "development":
    urlpatterns += i18n_patterns(path("admin/i18n/", include("rosetta.urls"))) + [
        path("__debug__/", include("debug_toolbar.urls"))
    ]
    if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    else:
        urlpatterns += [
            re_path(
                r"^mediafiles/(?P<path>.*)$",
                serve,
                {"document_root": settings.MEDIA_ROOT},
            ),
        ]

    # import debug_toolbar
    # from rest_framework import routers
    # from apps.notifications.api.urls import router as router_notifications

    # router = routers.DefaultRouter()
    # router.registry.extend(router_notifications.registry)

    # urlpatterns += [
    #     path('api/', include('apps.profiles.api.urls')),
    #     path('api/', include('apps.notifications.api.urls')),
    #     # path('api/', include(router.urls)),
    #     # path('__debug__/', include(debug_toolbar.urls)),
    # ]
else:
    urlpatterns += [
        re_path(
            r"^mediafiles/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}
        ),
    ]

apps/profiles/models.py
import os
import uuid
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

from cloudinary.models import CloudinaryField
from apps.profiles.managers import ProfileManager
from apps.utils.function import rename_profile_img
from config.settings import ENV

User = get_user_model()

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    uid = models.CharField(_("code identifiant"), max_length=500, blank=True)
    pseudo = models.CharField(_("nom d'utilisateur"), max_length=48, blank=True, unique=True)
    bio = models.CharField(_("titre du profil"), max_length=250, blank=True)
    birth_date = models.DateField(_("date de naissence"), null=True, blank=True)
    
    # img_profile = CloudinaryField('photo de profile', blank=True, null=True, default="https://res.cloudinary.com/dm68aag3e/image/upload/v1649743168/default-img-profile_hrhx6z.jpg")
    # img_bg = CloudinaryField('photo de couverture', blank=True, null=True, default="https://res.cloudinary.com/dm68aag3e/image/upload/v1649743327/default-img-bg_zbeoo4.jpg")
    img_profile = models.ImageField(_("photo de profile"), upload_to=rename_profile_img, default="mediafiles/default/profile_jyytyz.jpg", blank=True, null=True)
    img_bg = models.ImageField(_("photo de couverture"), upload_to=rename_profile_img, default="mediafiles/default/bg_r0siq1.jpg", blank=True, null=True)
    img_profile_str = models.CharField(max_length=500, default="https://res.cloudinary.com/dm68aag3e/image/upload/v1649743168/default-img-profile_hrhx6z.jpg", blank=True, null=True)
    img_bg_str = models.CharField(max_length=500, default="https://res.cloudinary.com/dm68aag3e/image/upload/v1649743327/default-img-bg_zbeoo4.jpg", blank=True, null=True)
    is_fixture = models.BooleanField(default=False)
    is_updating_img_profile = models.BooleanField(_("is updating img profile"), default=False)
    is_updating_img_bg = models.BooleanField(_("is updating img bg"), default=False)
    class GenderChoices(models.TextChoices):
        male = 'M', _('Masculin')
        female = 'F', _('Féminin')
    
    gender = models.CharField(_("sexe"), max_length=1, blank=True, choices=GenderChoices.choices)
    phone = models.CharField(_("téléphone"), max_length=20, blank=True)
    adress = models.CharField(_("adresse"), max_length=128, blank=True)
    town = models.CharField(_("ville"), max_length=68, blank=True)
    region = models.CharField(_("région"), max_length=68, blank=True)
    zipcode = models.CharField(_("code postal"), max_length=22, blank=True)
    country = models.CharField(_("pays"), max_length=45, blank=True)
    description = models.TextField(_("description"), blank=True)
    link_linkedin = models.URLField(_("lien de votre profil linkedin"), blank=True)
    link_gitthub = models.URLField(_("lien de votre gitthub"), blank=True)
    link_twitter = models.URLField(_("lien de votre twitter"), blank=True)
    link_mysite = models.URLField(_("lien de votre site web"), blank=True)
    number_views = models.IntegerField(_('Nombre de vue profil'), default=0, blank=True, null=True)
    friends = models.ManyToManyField(User, blank=True, related_name='friends')    
    date_updated = models.DateTimeField(_("date de modification"), auto_now=True)
    
    objects = ProfileManager()
    
    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"
    
    def save(self, *args, **kwargs):
        if self.uid == "":
            self.uid = str(uuid.uuid4()).replace('-', '') + str(uuid.uuid4()).replace('-', '') + str(uuid.uuid4()).replace('-', '') + str(uuid.uuid4()).replace('-', '') + str(uuid.uuid4()).replace('-', '') + str(uuid.uuid4()).replace('-', '') + str(uuid.uuid4()).replace('-', '') + str(uuid.uuid4()).replace('-', '') + str(uuid.uuid4()).replace('-', '') + str(uuid.uuid4()).replace('-', '') + str(self.user.id)
        return super().save(*args, **kwargs)
    
    def get_friends(self):
        return self.friends.all()
    
    def get_number_friends(self):
        return self.friends.all().count()
    
    class Meta:
        verbose_name = _('Profile')
        verbose_name_plural = _('Profiles')
        ordering = ['-date_updated']
        
    

apps/profiles/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model

from apps.profiles.models import Profile

User = get_user_model()


class ProfileForm(forms.ModelForm):
    # img_profile = forms.ImageField(required=False, widget=forms.FileInput(
    #     attrs={'class':'form-control-profile'}))
    # img_bg = forms.ImageField(required=False, widget=forms.FileInput(
    #     attrs={'class':'form-control-profile'}))
    # img_profile_clear = forms.BooleanField(required=False, widget=forms.CheckboxInput(
    #     attrs={'class':'form-control-profile'}))
    class Meta:
        model = Profile
        exclude = (
            "user",
            "uid",
            "phone",
            "adress",
            "number_views",
            "gender",
            "birth_date",
            "friends",
            "is_updating_img_profile",
            "is_updating_img_bg",
            "is_fixture",
            "img_profile_str",
            "img_bg_str",
        )
        widgets = {
            "pseudo": forms.TextInput(attrs={"class": "form-control-profile"}),
            "bio": forms.TextInput(attrs={"class": "form-control-profile"}),
            # 'img_profile': forms.FileInput(attrs={'class': 'form-control-profile'}),
            # 'img_bg': forms.FileInput(attrs={'class': 'form-control-profile'}),
            # 'phone': forms.TextInput(attrs={'class': 'form-control-profile'}),
            # 'adress': forms.TextInput(attrs={'class': 'form-control-profile'}),
            "town": forms.TextInput(attrs={"class": "form-control-profile"}),
            "region": forms.TextInput(attrs={"class": "form-control-profile"}),
            "zipcode": forms.TextInput(attrs={"class": "form-control-profile"}),
            "country": forms.TextInput(attrs={"class": "form-control-profile"}),
            "description": forms.Textarea(
                attrs={"cols": "80", "rows": "8", "class": "form-control-profile"}
            ),
            "link_linkedin": forms.TextInput(attrs={"class": "form-control-profile"}),
            "link_gitthub": forms.TextInput(attrs={"class": "form-control-profile"}),
            "link_twitter": forms.TextInput(attrs={"class": "form-control-profile"}),
            "link_mysite": forms.TextInput(attrs={"class": "form-control-profile"}),
        }


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
        )
        widgets = {
            "first_name": forms.TextInput(attrs={"class": "form-control-profile"}),
            "last_name": forms.TextInput(attrs={"class": "form-control-profile"}),
        }

apps/profiles/api/views.py
from django.shortcuts import get_object_or_404

from rest_framework.decorators import api_view
from rest_framework.response import Response
from apps.comments.models import Comment
from apps.post.models import Post

from apps.profiles.api.serializers import ProfileSerializer
from apps.profiles.models import Profile


@api_view()
def get_list_profiles(request):
    qs = Profile.objects.select_related('user').all()
    serializers = ProfileSerializer(qs, many=True)
    # print("IP Address for debug-toolbar: " + request.META['REMOTE_ADDR'])
    return Response(serializers.data)


@api_view()
def get_profile(request, id):
    qs = get_object_or_404(Profile, pk=id)
    serializer = ProfileSerializer(qs)
    # print(serializer.data)
    return Response(serializer.data)

apps/profiles/views.py
import os
import datetime
import cloudinary

from django.http import HttpResponseNotFound
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

from config.settings import ENV

User = get_user_model()
from apps.profiles.models import Profile
from apps.profiles.forms import ProfileForm, UserProfileForm
from apps.notifications.models import Notification
from apps.friends.views import list_relation_receiver_and_sender
from apps.chat.templatetags.chat import add_2_hour


@login_required(login_url='sign_in')
def profile(request, pseudo):
    try:
        profile = Profile.objects.select_related('user').get(pseudo=pseudo)
        if not profile.user.is_email_verified:
            return HttpResponseNotFound('<h1>Page not found</h1>')
    except:
        return HttpResponseNotFound('<h1>Page not found</h1>')
    if request.user != profile.user:
        if request.user.is_superuser == False:
            if Notification.objects.filter(type_notif='seen_profile', from_user=request.user, to_user=profile.user).exists():
                last_notif = Notification.objects.filter(type_notif='seen_profile', from_user=request.user, to_user=profile.user).last()
                date_diff = datetime.datetime.now() - add_2_hour(last_notif.date_created.replace(tzinfo=None))
                if date_diff.total_seconds() > 3600:
                    last_notif.delete()
                    
                    Notification.objects.create(type_notif='seen_profile', from_user=request.user, to_user=profile.user)
                    profile.number_views = profile.number_views + 1
                    profile.save()
            else:
                Notification.objects.create(type_notif='seen_profile', from_user=request.user, to_user=profile.user)
                profile.number_views = profile.number_views + 1
                profile.save()
    template = "profiles/profiles.html"
    context = list_relation_receiver_and_sender(request)
    context.update(
        {
            'profile': profile,
        }
    )
    return render(request, template, context=context)


@login_required(login_url='sign_in')
def update_profile(request):
    user = request.user
    user_profile_form = UserProfileForm(instance=user)
    profile_form = ProfileForm(instance=user.profile)
    profile = Profile.objects.get(user=user)
    is_updating_img_profile = False
    is_updating_img_bg = False
    if request.method == 'POST':
        user_profile_form = UserProfileForm(request.POST, instance=user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=user.profile)
        if profile_form.is_valid() and user_profile_form.is_valid():
            if len(request.FILES) != 0:
                for key, value in request.FILES.items():
                    if ENV == 'production':
                        if key == 'img_profile':
                            if profile.is_updating_img_profile:
                                cloudinary.uploader.destroy(str(profile.img_profile))
                            else:
                                is_updating_img_profile = True
                        if key == 'img_bg':
                            if profile.is_updating_img_bg:
                                cloudinary.uploader.destroy(str(profile.img_bg))
                            else:
                                is_updating_img_bg = True
                    else:
                        if key == 'img_profile':
                            if profile.is_updating_img_profile:
                                try:
                                    os.remove(profile.img_profile.path)
                                except:
                                    cloudinary.uploader.destroy(str(profile.img_profile))
                            else:
                                is_updating_img_profile = True
                        if key == 'img_bg':
                            if profile.is_updating_img_bg:
                                try:
                                    os.remove(profile.img_bg.path)
                                except:
                                    cloudinary.uploader.destroy(str(profile.img_bg))
                            else:
                                is_updating_img_bg = True
            user_profile_form.save()
            profile_form.save()
            profile_user = Profile.objects.get(user=user)
            if is_updating_img_profile:
                profile_user.is_updating_img_profile = True
            if is_updating_img_bg:
                profile_user.is_updating_img_bg = True
            profile_user.save()
            return redirect('profiles:profile', pseudo=user.profile.pseudo)
    template = "profiles/update.html"
    context = {
        'user_profile_form' : user_profile_form,
        'profile_form' : profile_form,
    }
    return render(request, template, context=context)

templates/profiles/profiles.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load cloudinary %}
{% load chat %}
{% load i18n %}


{% block title %} {{profile.user.first_name}} {{profile.user.last_name}} {% endblock title %}


{% block style %}
<link rel="shortcut icon" href=" {% static 'home/svg/linkedin-cust.svg' %} " type="image/x-icon">
<link rel="stylesheet" href=" {% static 'components/css/style.css' %}" />
<link rel="stylesheet" href=" {% static 'profiles/css/style.css' %} " />
{% endblock style %}

<!-- Navbar -->
{% block navbar %} {% include 'home/components/navbar2.html' %} {% endblock navbar %}

{% block content %}
<main class="main-profile">
  <div class="container-left">
    <section class="profile-info">
      <div class="container-info">
        <div class="info-img-bg">
          <img class="img_bg" src="
              {% if profile.is_fixture %}
                {{ profile.img_bg_str }}
              {% else %}
                {% if profile.img_bg %}
                  {{ profile.img_bg.url }}
                {% else %}
                  {% static 'home/img/default-img-bg.jpg' %}
                {% endif %}
              {% endif %}
            " alt="Couverture">
        </div>
        <img class="img_profile" src="
            {% if profile.is_fixture %}
              {{ profile.img_profile_str }}
            {% else %}
              {% if profile.img_profile %}
                {{ profile.img_profile.url }}
              {% else %}
                {% static 'home/img/default-img-profile.jpg' %}
              {% endif %}
            {% endif %}
          " alt="Profile">
        <div class="info-content">
          <h2>{{profile.user.first_name}} {{profile.user.last_name}} <span id="point-separator-style"></span>
            <small>@{{profile.pseudo}}</small>
          </h2>
          <p>{{profile.bio}}</p>

          {% if profile.country or profile.region or profile.town %}
          <div class="box-location">
            <img src="{% static 'home/svg/location.svg' %}">
            <p>
              {% if profile.country %}
              {{profile.country|title}}
              <span id="point-separator-style"></span>
              {% endif %}

              {% if profile.region %}
              {{profile.region|title}}
              <span id=" point-separator-style"></span>
              {% endif %}
              {{profile.town|title}}
            </p>
          </div>
          {% endif %}

          {% comment %}
          {% if profile.user.email %}
          <div class="box-tel">
            <img src="{% static 'home/svg/email.svg' %}">
            <p> {{profile.user.email}} </p>
          </div>
          {% endif %}

          {% if profile.phone %}
          <div class="box-tel">
            <img src="{% static 'home/svg/phone.svg' %}">
            <p>{{profile.phone}}</p>
          </div>
          {% endif %}
          {% endcomment %}

          <div class="box-friends">
            <img src="{% static 'home/svg/friends.svg' %}">

            {% if profile.user == request.user %}
            <a href="{% url 'friends:my_friends' %}">
              {{profile.friends.count}}
              {% if profile.friends.count > 1 %}
              relations
              {% else %}
              relation
              {% endif %}
            </a>
            {% else %}
            <p>
              {{profile.friends.count}}
              {% if profile.friends.count > 1 %}
              relations
              {% else %}
              relation
              {% endif %}
            </p>
            {% endif %}
          </div>

          {% if profile.user == request.user %}
          <!-- <div class="btn-container-update-profile"> -->
          <a class="btn-container-update-profile" href="{% url 'profiles:update_profile' %}">{% translate 'Modifier mon profil' %}</a>
          <!-- </div> -->
          {% endif %}

          {% if profile.user not in list_receiver and profile.user not in list_sender and user != profile.user and profile.user not in request.user.profile.friends.all %}
          <form action="{% url 'friends:send_invitation' %}" method="POST" class="to-invites-add-friends">
            {% csrf_token %}
            <input type="hidden" name="profile_id" value="{{profile.id}}">
            <input type="hidden" name="redirect" value="profile">
            <button class="btn-add-friends" type="submit">{% translate 'Envoyer une invitation' %}</button>
          </form>
          {% elif profile.user in request.user.profile.friends.all %}
          <a class="btn-container-update-profile" href="{% url 'chats:chatroom' uid=profile.uid %}">{% translate 'Envoyer un message' %}</a>
          {% endif %}


          {% comment %}
          {% if request.user in profile.friends.all %}
          <!-- <form action="{% url 'friends:remove_invitation' %}" method="POST" class="to-invites-add-friends">
            {% csrf_token %}
            <input type="hidden" name="profile_id" value="{{profile.id}}">
            <input type="hidden" name="redirect" value="profile">
            <button class="btn-remove-friends" type="submit">Supprimer</button>
          </form> -->
          {% endif %}
          {% endcomment %}

        </div>
      </div>
    </section>

    <section class="profile-description">
      <h2>Infos</h2>
      <div class="container-description">
        {% if profile.description %}
        <p>
          {{ profile.description|linebreaksbr }}
        </p>
        {% else %}
        <p>
          Lorem Ipsum is simply dummy text of the printing and typesetting industry.
          Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
          when an unknown printer took a galley of type and scrambled it to make a type specimen book.
          <br>
          <br>
          It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially
          unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum
          passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem
          Ipsum.
          <br>
          <br>
          Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin
          literature from 45 BC, making it over 2000 years old.
        </p>
        {% endif %}
      </div>
    </section>
  </div>

  <div class="container-right">
    <aside class="asd-info-stat">
      {% if profile.user == request.user %}
      <!-- <div class="btn-container-update-profile">
        <a href="{% url 'profiles:update_profile' %}">Modifier le profile</a>
      </div> -->
      {% endif %}

      {% if profile.user == request.user %}
      <div class="statistic-profile">
        <div class="num-vue statistic">
          <span class="statistic-text">{% translate 'Vues de votre profil' %}</span>
          <span class="statistic-num">
            {% if profile.number_views %}
            {{profile.number_views}}
            {% else %}
            0
            {% endif %}
          </span>
        </div>
        <div class="num-post statistic">
          <span class="statistic-text">{% translate 'Nombre de post' %}</span>
          <span class="statistic-num">{{profile.user.post.count}}</span>
        </div>
      </div>
      {% endif %}

      {% if profile.link_linkedin or profile.link_twitter or profile.link_gitthub or profile.link_mysite %}
      <div class="others-link">
        {% if profile.link_linkedin %}
        <div class="link-pro">
          <img src="{% static 'home/svg/linkedin.svg' %}" class="link-pro-icon">
          <a href="{{profile.link_linkedin}}" class="link-pro-link" target="_blank">linkedin</a>
        </div>
        {% endif %}

        {% if profile.link_twitter %}
        <div class="link-pro">
          <img src="{% static 'home/svg/twitter.svg' %}" class="link-pro-icon">
          <a href="{{profile.link_twitter}}" class="link-pro-link" target="_blank">twitter</a>
        </div>
        {% endif %}

        {% if profile.link_gitthub %}
        <div class="link-pro">
          <img src="{% static 'home/svg/github.svg' %}" class="link-pro-icon">
          <a href="{{profile.link_gitthub}}" class="link-pro-link" target="_blank">github</a>
        </div>
        {% endif %}

        {% if profile.link_mysite %}
        <div class="link-pro">
          <img src="{% static 'home/svg/web.svg' %}" class="link-pro-icon">
          <a href="{{profile.link_mysite}}" class="link-pro-link" target="_blank">mysite</a>
        </div>
        {% endif %}
      </div>
      {% endif %}
    </aside>

    {% if profile.friends.all|length >= 1 %}
    <aside class="asd-rs">
      <div class="profile-friends-box-container">
        <h4>
          {% if profile.user == request.user %}
          {% translate 'Vos Relations' %}
          {% else %}
          {% translate 'Les connaissez-vous ?' %}
          {% endif %}
        </h4>
        <div class="profile-friends-container">
          {% for obj in profile.friends.all|slice:"5" %}
          {% if obj != request.user %}
          <a href="{% url 'profiles:profile' pseudo=obj.profile.pseudo %}">
            <div class="profile-friends-box">
              <img class="profile-img-friends" src="
                  {% if obj.profile.is_fixture %}
                    {{ obj.profile.img_profile_str }}
                  {% else %}
                    {% if obj.profile.img_profile %}
                      {{ obj.profile.img_profile.url }}
                    {% else %}
                      {% static 'home/svg/default-img-profile.jpg' %}
                    {% endif %}
                  {% endif %}
                ">
              <div class="profile-friends-info-container">
                <strong>{{obj.first_name}} {{obj.last_name}}</strong>
                <p>{{obj.profile.bio}}</p>
                {% if obj in request.user.profile.friends.all %}
                {% if obj.last_logout %}
                <P>
                  {% if obj.last_logout > obj.last_login %}
                  {% translate 'En ligne' %} {{obj.last_logout|naturaltime|timestr}}
                  {% else %}
                  {% translate 'En ligne maintenant' %}
                  {% endif %}
                </P>
                {% endif %}
                {% endif %}
              </div>
            </div>
          </a>
          {% endif %}
          {% endfor %}
        </div>

        {% if profile.user == request.user %}
        {% if profile.friends.all|length > 5 %}
        <div class="voir-plus-box">
          <a href="{% url 'friends:my_friends' %}" class="voir-plus">{% translate 'Voir plus' %}</a>
        </div>
        {% endif %}
        {% endif %}
      </div>
    </aside>
    {% endif %}
  </div>
</main>
{% endblock content %}

<!-- Footer -->
{% block footer %} {% include 'home/components/footer.html' %} {% endblock footer %}

{% block js %}
<script type="text/javascript" src=" {% static 'components/js/index.js' %} "></script>
<script type="text/javascript" src=" {% static 'notifications/js/notifications.js' %} "></script>
{% endblock js %}

templates/profiles/update.html
{% extends 'base.html' %}
{% load static %}
{% load cloudinary %}
{% load i18n %}


{% block title %} Update profil {{profile.user.first_name}} {{profile.user.last_name}} {% endblock title %}


{% block style %}
<link rel="shortcut icon" href=" {% static 'home/svg/linkedin-cust.svg' %} " type="image/x-icon">
<link rel="stylesheet" href=" {% static 'components/css/style.css' %}" />
<link rel="stylesheet" href=" {% static 'profiles/css/style.css' %} " />
{% endblock style %}

<!-- Navbar -->
{% block navbar %} {% include 'home/components/navbar2.html' %} {% endblock navbar %}

{% block content %}
<main class="main-profile-update">

  <div class="update-porfile-container">
    <h2>{% translate 'Modifier le profil' %}</h2>

    <form action="" method="POST" enctype="multipart/form-data" class="form-profile-update">
      {% csrf_token %}

      {% for field in user_profile_form %}
      <div class="container-form-control-profile">
        <label for="id_{{field.name}}">{{field.label}}</label>
        {{field}}
      </div>
      {% endfor %}

      {% for field in profile_form %}
      <div class="container-form-control-profile">
        <label for="id_{{field.name}}">{{field.label}}</label>
        {{field}}
      </div>
      {% endfor %}

      <input type="submit" value="Enregistrer">
    </form>
  </div>

</main>
{% endblock content %}

<!-- Footer -->
{% block footer %} {% include 'home/components/footer.html' %} {% endblock footer %}

{% block js %}
<script type="text/javascript" src=" {% static 'components/js/index.js' %} "></script>
<script type="text/javascript" src=" {% static 'notifications/js/notifications.js' %} "></script>
{% endblock js %}